// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGr8Eb9xcNkXtU2xHC8LL4ITWlTGCO4O0',
    appId: '1:743142802789:web:a19c6a6ea7cdc0224c8d8c',
    messagingSenderId: '743142802789',
    projectId: 'mtsp-fa9ff',
    authDomain: 'mtsp-fa9ff.firebaseapp.com',
    storageBucket: 'mtsp-fa9ff.appspot.com',
    measurementId: 'G-148VNLTDWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAacL4jwzScGB96zV_rfzc6w6rsJOsydLY',
    appId: '1:743142802789:android:76c882b279b7108f4c8d8c',
    messagingSenderId: '743142802789',
    projectId: 'mtsp-fa9ff',
    storageBucket: 'mtsp-fa9ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBACdbuhYEG5hck4aHIFHVOx7TqjMDZ1_U',
    appId: '1:743142802789:ios:74bfe1425fe05c8d4c8d8c',
    messagingSenderId: '743142802789',
    projectId: 'mtsp-fa9ff',
    storageBucket: 'mtsp-fa9ff.appspot.com',
    iosBundleId: 'com.example.mtsp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBACdbuhYEG5hck4aHIFHVOx7TqjMDZ1_U',
    appId: '1:743142802789:ios:74bfe1425fe05c8d4c8d8c',
    messagingSenderId: '743142802789',
    projectId: 'mtsp-fa9ff',
    storageBucket: 'mtsp-fa9ff.appspot.com',
    iosBundleId: 'com.example.mtsp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGr8Eb9xcNkXtU2xHC8LL4ITWlTGCO4O0',
    appId: '1:743142802789:web:d398558c949d89ab4c8d8c',
    messagingSenderId: '743142802789',
    projectId: 'mtsp-fa9ff',
    authDomain: 'mtsp-fa9ff.firebaseapp.com',
    storageBucket: 'mtsp-fa9ff.appspot.com',
    measurementId: 'G-0V64H1PP9D',
  );

}